In [72]:
import pandas as pd
import numpy as np 
df = pd.read_excel('dataset.xlsx')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   id       48 non-null     int64  
 1   text     48 non-null     object 
 2   subject  0 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.2+ KB


In [71]:
df.head()

id                                               text  subject
0   0  Açılış törenlerinde binlerce kişiyi bir araya ...      NaN
1   1  Okulun sitesinde paylaşılmış. Fiyatlar şaka gi...      NaN
2   2  merhaba, 2. sınıfların kayıt günü bugün olduğu...      NaN
3   3  Bu nasıl bir rezilliktir ya sabah saat 9 dan b...      NaN
4   4  Dalga geçer gibi mat102 dersini ilk kez bu dön...      NaN

In [3]:
df['text'][5]

'Ders programı hala açıklanmadı. Son sınıfım bir sürü seçmeli dersim var hangisini alacağımı bilmiyorum ve yarın ders seçimi var. Okulu arıyorum yardımcı olan yok. Şaşırtmadın yine Işık Üniversitesi.'

In [4]:
from collections import Counter
Counter(" ".join(df["text"]).split()).most_common(100)

[('bir', 59),
 ('bu', 53),
 ('ve', 42),
 ('ne', 21),
 ('de', 21),
 ('için', 20),
 ('kadar', 18),
 ('da', 18),
 ('çok', 17),
 ('gibi', 13),
 ('ben', 13),
 ('ama', 13),
 ('şey', 13),
 ('1', 12),
 ('var', 12),
 ('bi', 12),
 ('o', 12),
 ('mi', 12),
 ('en', 12),
 ('her', 12),
 ('bile', 11),
 ('Bu', 11),
 ('daha', 11),
 ('okul', 11),
 ('sadece', 10),
 ('ders', 10),
 ('başka', 10),
 ('ki', 10),
 ('yok', 10),
 ('öğrenci', 9),
 ('okulun', 9),
 ('olan', 9),
 ('online', 9),
 ('ile', 9),
 ('fakat', 8),
 ('mı', 8),
 ('gerçekten', 8),
 ('nasıl', 7),
 ('ya', 7),
 ('dönem', 7),
 ('olarak', 7),
 ('artık', 7),
 ('bize', 7),
 ('lütfen', 6),
 ('yine', 6),
 ('kota', 6),
 ('Bir', 6),
 ('2', 6),
 ('şu', 6),
 ('olduğu', 5),
 ('mail', 5),
 ('neden', 5),
 ('acaba', 5),
 ('için.', 5),
 ('düzgün', 5),
 ('diyelim', 5),
 ('proje', 5),
 ('arkadaşlar', 5),
 ('Işık', 5),
 ('öyle', 5),
 ('değil.', 5),
 ('zaten', 5),
 ('aynı', 5),
 ('respondus', 5),
 ('bazı', 5),
 ('yurt', 5),
 ('yani', 5),
 ('insanlar', 5),
 ('hiçbir',

In [5]:
set(df.text.apply(list).sum())

{' ',
 '!',
 '"',
 '%',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'R',
 'S',
 'T',
 'U',
 'V',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'y',
 'z',
 'Ç',
 'Ö',
 'Ü',
 'ç',
 'ö',
 'ü',
 'ğ',
 'İ',
 'ı',
 'Ş',
 'ş'}

In [6]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing import sequence

In [7]:
tokenizer = keras.preprocessing.text.Tokenizer(char_level=True)
tokenizer.fit_on_texts(df['text'])

In [9]:
print(len(df['text']))

48


In [10]:
tokenizer.texts_to_sequences(["Ders"])

[[11, 3, 5, 13]]

In [11]:
tokenizer.sequences_to_texts([[11, 3, 5, 13]])

['d e r s']

In [14]:
tokenizer.sequences_to_texts([[13, 14 ,2 ,12 ,17]]) 

['s u a y b']

In [15]:
max_id = len(tokenizer.word_index) # number of distinct characters
dataset_size = tokenizer.document_count # total number of characters
print(max_id)
print(dataset_size)

55
48


In [16]:
df['text'][0]

'Açılış törenlerinde binlerce kişiyi bir araya toplayan, İşletme ekonominin düzenlediği etkinlikte maskesiz, mesafesiz eğlence, etkinlik ve eğitimler düzenleyen ve bunu açıkça paylaşan fakat 40 kişilik sınıfları bile virüsü bahane ederek uzaktan eğitim almaya mecbur kılan bir ışık üniversitesi bırakıyorum buraya'

In [20]:
[encoded] = np.array(tokenizer.texts_to_sequences([" ".join(df["text"]).split()])) - 1
train_size = dataset_size * 90 // 100
#dataset = tf.data.Dataset.from_tensor_slices(df['text'])
dataset = tf.data.Dataset.from_tensor_slices(encoded[:train_size])

In [21]:
print(encoded.shape)

(43,)


In [22]:
n_steps = 100
window_length = n_steps + 1 # target = input shifted 1 character ahead
dataset = dataset.repeat().window(window_length, shift=1, drop_remainder=True)

In [23]:
dataset = dataset.flat_map(lambda window: window.batch(window_length))

In [24]:
for a in dataset.take(5):
  print(a)

tf.Tensor(
[32 14 43 14  1 31 14 14 14 32 14 32 32 32 14 32 14  2 23 31 34 32 34 31
 41 32 32 14 34 34 39 32 48 31 34 34 32 32 14 14 14 39 48 32 14 43 14  1
 31 14 14 14 32 14 32 32 32 14 32 14  2 23 31 34 32 34 31 41 32 32 14 34
 34 39 32 48 31 34 34 32 32 14 14 14 39 48 32 14 43 14  1 31 14 14 14 32
 14 32 32 32 14], shape=(101,), dtype=int64)
tf.Tensor(
[14 43 14  1 31 14 14 14 32 14 32 32 32 14 32 14  2 23 31 34 32 34 31 41
 32 32 14 34 34 39 32 48 31 34 34 32 32 14 14 14 39 48 32 14 43 14  1 31
 14 14 14 32 14 32 32 32 14 32 14  2 23 31 34 32 34 31 41 32 32 14 34 34
 39 32 48 31 34 34 32 32 14 14 14 39 48 32 14 43 14  1 31 14 14 14 32 14
 32 32 32 14 32], shape=(101,), dtype=int64)
tf.Tensor(
[43 14  1 31 14 14 14 32 14 32 32 32 14 32 14  2 23 31 34 32 34 31 41 32
 32 14 34 34 39 32 48 31 34 34 32 32 14 14 14 39 48 32 14 43 14  1 31 14
 14 14 32 14 32 32 32 14 32 14  2 23 31 34 32 34 31 41 32 32 14 34 34 39
 32 48 31 34 34 32 32 14 14 14 39 48 32 14 43 14  1 31 14 14 14 32 14 32
 

In [25]:
np.random.seed(42)
tf.random.set_seed(42)

In [26]:
batch_size = 32
dataset = dataset.shuffle(10000).batch(batch_size)
dataset = dataset.map(lambda windows: (windows[:, :-1], windows[:, 1:]))

In [27]:
dataset = dataset.map(
    lambda X_batch, Y_batch: (tf.one_hot(X_batch, depth=max_id), Y_batch))

In [28]:
dataset = dataset.prefetch(1)

In [29]:
for X_batch, Y_batch in dataset.take(1):
    print(X_batch.shape, Y_batch.shape)

(32, 100, 55) (32, 100)


In [30]:
print(tf.argmax(X_batch[0,0:10,:],axis=1))

tf.Tensor([32 14 43 14  1 31 14 14 14 32], shape=(10,), dtype=int64)


In [31]:
keras.backend.clear_session()
model = keras.models.Sequential([
    keras.layers.GRU(8, return_sequences=True, input_shape=[None, max_id]
                     # no dropout in stateful RNN (https://github.com/ageron/handson-ml2/issues/32)
                     # dropout=0.2, recurrent_dropout=0.2,
                     ),
    keras.layers.GRU(8, return_sequences=True
                     # dropout=0.2, recurrent_dropout=0.2
                    ),
    keras.layers.TimeDistributed(keras.layers.Dense(max_id,
                                                    activation="softmax"))
])
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam")
history = model.fit(dataset, steps_per_epoch=train_size // batch_size,
                    epochs=5)

Epoch 1/5
1/1 [==============================] - 11s 11s/step - loss: 3.9920
Epoch 2/5
1/1 [==============================] - 0s 36ms/step - loss: 3.9880
Epoch 3/5
1/1 [==============================] - 0s 38ms/step - loss: 3.9843
Epoch 4/5
1/1 [==============================] - 0s 37ms/step - loss: 3.9804
Epoch 5/5
1/1 [==============================] - 0s 40ms/step - loss: 3.9762


In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru (GRU)                   (None, None, 8)           1560      
                                                                 
 gru_1 (GRU)                 (None, None, 8)           432       
                                                                 
 time_distributed (TimeDistr  (None, None, 55)         495       
 ibuted)                                                         
                                                                 
Total params: 2,487
Trainable params: 2,487
Non-trainable params: 0
_________________________________________________________________


In [35]:
def preprocess(texts):
    X = np.array(tokenizer.texts_to_sequences(texts)) - 1
    return tf.one_hot(X, max_id)

In [40]:
X_new = preprocess(["Ders"])
Y_pred = model.predict(X_new)
classes_x=np.argmax(Y_pred,axis=1)
tokenizer.sequences_to_texts(classes_x + 1)[0][-1] # 1st sentence, last char

'i'

In [50]:
def next_char(text, temperature=1):
    X_new = preprocess([text])
    y_proba = model.predict(X_new)[0, -1:, :]
    rescaled_logits = tf.math.log(y_proba) / temperature
    char_id = tf.random.categorical(rescaled_logits, num_samples=1) + 1 #argmax
    return tokenizer.sequences_to_texts(char_id.numpy())[0]

In [51]:
def complete_text(text, n_chars=50, temperature=1):
    for _ in range(n_chars):
        text += next_char(text, temperature)
    return text

In [53]:
tf.random.set_seed(42)

print(complete_text("Ders", temperature=1))

Ders%;0f;ds(nsk.ö'tia3̇%17'yv1zm?:2-ğ ;.h2!if 9it)e4̇d


**Comments :**

1) If we want better complete text results we need to use Turkish tokenizer. Results are not so good because the system is for English words.

2) In this dataset, sentences are not so good, I mean sentences structure is 
broken so model is not training so good.

3) Other thing is dataset is small. If we use a dataset which includes 2000 sentences text, results can be better than this.

For Example: Turkish Pre-trained Word2Vec Model, Zemberek



Another trying

In [55]:
from tensorflow.python.keras.preprocessing.text import Tokenizer

In [56]:
X=df['text'].values.tolist()

In [57]:
num_words = 50
tokenizer = Tokenizer(num_words = num_words)

In [58]:
tokenizer.fit_on_texts(X)

In [59]:
counter = 0
for word in tokenizer.word_index:
    counter = counter + 1
    print(counter, "-> ", word)
    if(counter == 20):
        break

1 ->  bu
2 ->  bir
3 ->  ve
4 ->  için
5 ->  ne
6 ->  de
7 ->  kadar
8 ->  var
9 ->  da
10 ->  1
11 ->  çok
12 ->  okul
13 ->  ben
14 ->  her
15 ->  gibi
16 ->  mi
17 ->  ama
18 ->  şey
19 ->  bile
20 ->  bi


In [60]:
X_train_tokens = tokenizer.texts_to_sequences(X)

In [62]:
X[20]

"Ağustos'ta ödeyip ödeme dekontunu mail atıp teyidini aldığım yurt borcumu sistemden silmedikleri ve 2 gündür ne bir mailime ne de bir telefonuma cevap vermedikleri için ders seçemedim. Teşekkürler ışık üniversitesi, harika bir üniversite deneyimi yaşatıyorsun gerçekten."

In [64]:
np.array(X_train_tokens[20])

array([ 3, 36,  5,  2,  5,  6,  2,  4, 28, 47,  2, 21])

In [65]:
num_tokens = [len(tokens) for tokens in X_train_tokens]
num_tokens = np.array(num_tokens)
num_tokens

array([ 7, 17, 29, 11, 15,  9, 16,  2, 28,  3, 13, 13,  9, 29,  9, 12, 34,
        6, 16,  3, 12,  4, 22, 15, 26,  8,  8,  9, 13, 17,  8, 11, 11,  3,
       19, 15,  4, 12, 44, 19, 30, 13, 22, 29, 17, 17, 20, 27])

In [66]:
import math
max_tokens = np.mean(num_tokens) + 2*np.std(num_tokens)
max_tokens = math.ceil(max_tokens)
max_tokens

34

In [67]:
from tensorflow.python.keras.preprocessing.sequence import pad_sequences
X_train_pad = pad_sequences(X_train_tokens, maxlen = max_tokens)

In [68]:
idx = tokenizer.word_index
inverse_map = dict(zip(idx.values(), idx.keys()))

In [69]:
def tokens_to_string(tokens):
    words = (inverse_map[token] for token in tokens if token != 0)
    text = " ".join(words)
    return text